// Regenerates lib/features/settings/legal_content.dart from the phone app's legal/content.ts (which is itself generated from the
// website), so the Flutter app shows the same policies, word for word.
//
//   node --import tsx tool/sync_legal.mts            (from packages/mobile, after `npm ci` at the repo root)
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

const harness = resolve(process.argv[2] ?? resolve(import.meta.dirname, '../../..'));
const src = resolve(harness, 'packages/web/src/legal/content.ts');
const { POLICY_VERSION, POLICY_DATE, legalDocuments, legalLinks } = await import(pathToFileURL(src).href);

/** A Dart single-quoted string literal. */
const q = (s: string) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\$/g, '\\$').replace(/\n/g, '\\n')}'`;

const out: string[] = [];
out.push(`// GENERATED by tool/sync_legal.mts from packages/web/src/legal/content.ts (itself generated from the website). Do not edit by hand.
// The legal documents, stored in the app so they read without a connection.
// Plain text with two inline marks (see legal_rich.dart): [label](/path or https://…) for links and **bold**.

const policyVersion = ${q(POLICY_VERSION)};
const policyDate = ${q(POLICY_DATE)};

class LegalSection {
  const LegalSection(this.heading, {this.id, this.paragraphs = const [], this.items = const []});
  final String heading;
  final String? id;
  final List<String> paragraphs;
  final List<String> items;
}

class LegalDocument {
  const LegalDocument({required this.title, required this.description, required this.sections});
  final String title;
  final String description;
  final List<LegalSection> sections;
}

const legalDocuments = <String, LegalDocument>{`);
for (const [key, doc] of Object.entries(legalDocuments as Record<string, { title: string; description: string; sections: Array<{ heading: string; id?: string; paragraphs?: string[]; items?: string[] }> }>)) {
  out.push(`  ${q(key)}: LegalDocument(`);
  out.push(`    title: ${q(doc.title)},`);
  out.push(`    description: ${q(doc.description)},`);
  out.push(`    sections: [`);
  for (const s of doc.sections) {
    out.push(`      LegalSection(${q(s.heading)}${s.id ? `, id: ${q(s.id)}` : ''},`);
    for (const field of ['paragraphs', 'items'] as const) {
      const list = s[field];
      if (!list?.length) continue;
      out.push(`        ${field}: [`);
      for (const line of list) out.push(`          ${q(line)},`);
      out.push(`        ],`);
    }
    out.push(`      ),`);
  }
  out.push(`    ],`);
  out.push(`  ),`);
}
out.push(`};

const legalLinks = <(String, String)>[`);
for (const [key, label] of legalLinks as ReadonlyArray<readonly [string, string]>) out.push(`  (${q(key)}, ${q(label)}),`);
out.push(`];

/// The documents worth listing, in the website's order. ("legal" and "about" are website pages.)
final legalList = [
  for (final (key, label) in legalLinks)
    if (key != 'legal' && legalDocuments.containsKey(key)) (key: key, label: label),
];

/// The label of a document, for a page title.
String legalLabel(String key) {
  for (final d in legalList) {
    if (d.key == key) return d.label;
  }
  return 'Legal';
}
`);
writeFileSync(resolve(import.meta.dirname, '../lib/features/settings/legal_content.dart'), out.join('\n'));
console.log(`legal_content.dart: policy ${POLICY_VERSION}, ${Object.keys(legalDocuments).length} documents`);
