// GENERATED by scripts/sync-legal.mjs from escanor-web/lib/legal-content.ts. Do not edit here: change the website, then re-run it.
export const POLICY_VERSION = '2026-10-01';
export const POLICY_DATE = '1 October 2026';

export type LegalDocument = {
  title: string;
  description: string;
  sections: { heading: string; paragraphs: string[] }[];
};

export const legalDocuments: Record<string, LegalDocument> = {
  privacy: {
    title: 'Privacy policy',
    description: 'What information Escanor handles, why it is used, and how to raise a privacy request.',
    sections: [
      { heading: 'Who handles your information', paragraphs: [
        'Escanor is an engineering workspace that connects accounts, repositories, cloud services and local machines. Operator and privacy contact details are listed below. For workspace content supplied by an organisation, that organisation may determine the purposes of processing; contact your workspace administrator as well as us when exercising a request concerning that content.',
      ] },
      { heading: 'Information and purposes', paragraphs: [
        'Account: your name, email, identity-provider identifiers and authentication/session records are used to sign you in, maintain account security and manage membership.',
        'Connected services: provider permissions, access credentials, connection metadata, repository content, infrastructure details, activity and diagnostics are used to perform the operations you or your organisation request. The exact data depends on the integrations and permissions you enable.',
        'AI features: prompts, conversations, selected code, logs and tool results may be processed by the AI services configured for the requested feature. Do not include personal information, secrets or third-party content unless you are authorised to share it. Provider-specific retention and training terms must be checked for the deployed provider; this notice does not promise zero retention or no training by every provider.',
        'Billing: subscription identifiers, plan information, payment references and payment status are used for billing and reconciliation. Razorpay processes payments through its checkout and applies its own privacy terms. Never send card numbers, CVV, UPI PINs or OTPs to support.',
        'Support and security: information you provide in a complaint, account references and relevant diagnostic/security records are used to investigate issues, prevent abuse, meet applicable legal duties and respond to requests. Send the minimum information needed.',
      ] },
      { heading: 'The Escanor Android app', paragraphs: [
        'Each phone permission is asked for only when you first use the feature that needs it, and each can be refused or switched off later in Android settings. Refusing one stops only that feature.',
        'Microphone and voice: what you say to the assistant is turned into text by Android’s speech recognition (which, depending on the phone, may use Google’s speech service), and the text is sent to Escanor to work out what you asked. “Hey Escanor” runs only after you switch it on: it listens on the phone with a voice model it downloads once, shows a notification while it listens, and records or sends nothing until it hears the two words.',
        'Contacts and calls: contacts are read on the phone only when you ask to call someone by name, to find their number; they are not uploaded. The Phone permission is used only to place a call you asked for.',
        'Camera and notifications: the camera is used only to scan the pairing code shown by Escanor Desktop. Notifications carry alerts you chose; a device token is stored to deliver them and removed when you sign out.',
        'Phone control (Accessibility): only in the “with phone control” build, and only after the app explains what it does, you agree in the app, and you switch it on yourself in Android’s Accessibility settings. It then goes home or back, scrolls, taps a button by its name and types, only when you ask. To find a button or answer “what is on my screen”, it reads the text on the screen at that moment; that text stays on the phone and is not stored, sent to Escanor or used for advertising. Your agreement and any withdrawal are recorded in the consent ledger. Switch it off at any time in Android’s Accessibility settings.',
      ] },
      { heading: 'Your choices and lawful processing', paragraphs: [
        'Providing data for an optional integration is your choice. You may decline to connect it or disconnect it and revoke its access at the provider. Features requiring that data may then stop working. Revoking access stops future access but does not automatically erase previously stored records.',
        'A sign-in or payment is not consent to unrelated marketing, advertising or AI training. Processing that requires consent must have a specific notice and a separate affirmative choice. Use Privacy requests to withdraw consent, request review or correction, or ask for erasure and information about processing. Requests may require proportionate verification of your identity or authority; do not send identity documents unless securely requested.',
      ] },
      { heading: 'Sharing and international processing', paragraphs: [
        'Depending on the features used, information may be handled by hosting and database providers, identity providers such as Google or GitHub, Razorpay, configured AI providers, connected services and authorised workspace administrators. We may disclose information where required by a valid legal obligation. Each connected provider also has its own terms.',
        'A connected provider or hosting service may process information outside India. This page does not assert India-only hosting. Before publication, the operator must verify the actual recipient inventory, locations, contracts, equivalent protections where required, and applicable transfer restrictions. Request the current recipient and processing-location information through the privacy contact.',
      ] },
      { heading: 'Retention and security', paragraphs: [
        'Account and workspace information is needed while the relevant service is provided. Erasure requests must be assessed against the purpose of processing and any applicable tax, security, dispute, investigation or other statutory retention requirement. Disconnecting an integration, signing out or clearing browser storage does not delete server records, backups or records independently held by providers.',
        'Security controls include authenticated access and provider permissions. Browser session tokens remain in local storage; use a trusted device and sign out after use. Persistent workspace query and integration caches are disabled in this version. No service can guarantee absolute security. The operator must validate server retention periods, backup expiry, access reviews and incident procedures before approving this policy.',
      ] },
      { heading: 'Children, requests and changes', paragraphs: [
        'Escanor is intended for adults aged 18 or above acting on their own behalf or with authority for an organisation. Do not create an account for a child or upload children’s personal data without an approved lawful process. Report suspected collection of a child’s information to the privacy contact.',
        'The Privacy requests page explains access, correction, erasure, withdrawal, grievance and nomination requests. Rights and escalation routes depend on the applicable law and its commencement. DPDP provisions commence in phases; this policy does not represent all provisions as already operative. Statutory rights remain unaffected.',
        'Material changes should be communicated before introducing a new use of personal data and fresh consent obtained where required. The version date identifies this notice; merely updating it does not itself authorise a new processing purpose.',
      ] },
    ],
  },
  terms: {
    title: 'Terms of service', description: 'Conditions for authorised use of Escanor.',
    sections: [
      { heading: 'Eligibility and authority', paragraphs: ['Use Escanor only if you are at least 18 and legally able to enter a contract. When acting for an organisation, you must have its authority. Keep account and integration credentials secure and promptly report unauthorised access. Operator details appear below.'] },
      { heading: 'Connected services and automation', paragraphs: ['Connect only systems you own or are authorised to administer. Choose the minimum permissions needed and review proposed commands, deployments and AI-generated output before approving consequential actions. Automated actions can affect availability, cost, data and infrastructure. Maintain appropriate backups and change approvals.', 'Third-party services have their own terms, charges and availability. Escanor is not a law firm, and generated output is not professional legal, tax or regulatory advice. Human review remains necessary.'] },
      { heading: 'Your content and permitted use', paragraphs: ['You retain your rights in content you provide. You authorise processing of that content to provide the features you request, subject to the privacy notice and any applicable organisational agreement. This does not grant an unrestricted right to exploit your content.', 'Do not use the service for unauthorised access, malware, fraud, unlawful surveillance, infringement, harmful impersonation, exploitation of children, or other illegal conduct. The Acceptable use page provides further guidance and the Grievances page explains reporting.'] },
      { heading: 'Plans, renewal and cancellation', paragraphs: ['Check the plan, billing interval, total price, taxes and renewal conditions shown before purchase. Do not proceed if these are unclear. Third-party infrastructure charges may be separate. A subscription continues under the renewal terms you authorise until cancelled.', 'Use Dashboard → Settings → Billing to manage the organisation’s subscription if your role permits it. Read the Refunds and cancellation page before paying. Account deletion and subscription cancellation are separate requests. No clause excludes a refund, remedy or consumer right required by applicable law.'] },
      { heading: 'Suspension, disputes and changes', paragraphs: ['Access may be restricted where reasonably necessary to address misuse, a security threat or a lawful order. Where legally permitted, affected users should receive reasons and a route to contest the decision through the grievance contact.', 'Indian law applies subject to mandatory protections that apply to you. Nothing in these terms removes statutory consumer forum rights, privacy rights, or liability that cannot lawfully be excluded. Raise service disputes through support and then the grievance officer; this does not prevent using an available legal remedy.', 'Material changes to contractual terms must be notified and accepted where required before they apply. A date change on this page alone does not record your acceptance.'] },
    ],
  },
  cookies: {
    title: 'Cookies and browser storage', description: 'How browser storage supports the service and what clearing it does.',
    sections: [
      { heading: 'Sign-in and preferences', paragraphs: ['The web app stores access and refresh tokens, active organisation/workspace identifiers, theme and interface preferences in your browser. These support authentication, workspace selection and your chosen settings. Identity and payment providers may use their own cookies or storage during their flows.'] },
      { heading: 'Workspace data', paragraphs: ['Persistent query and integration caches are disabled in this version. Older caches using Escanor’s query and integration cache keys are cleared when the app initialises. Live query results remain in memory during use and are cleared at sign-out and organisation/workspace changes. This does not erase backend data.'] },
      { heading: 'Optional tracking', paragraphs: ['No advertising or marketing analytics tracker was identified in the reviewed root provider and landing-page flow. Integration analytics are product data, not a marketing-cookie category. If optional tracking is added, it must be inventoried and blocked until the required specific consent is obtained, with an equally accessible withdrawal control. This page does not claim to control storage created by external providers.'] },
      { heading: 'Managing storage', paragraphs: ['Sign out on shared devices. Browser site settings let you inspect or clear cookies and local storage for this site. Clearing site data signs you out and resets saved preferences, but is not an account deletion request. Use Privacy requests for server-side data requests.'] },
    ],
  },
  refunds: {
    title: 'Refunds and cancellation', description: 'How to stop renewal and raise a payment or refund issue.',
    sections: [
      { heading: 'Digital service and prices', paragraphs: ['Escanor provides online software services; physical shipping is not part of the subscription. Review the selected plan, billing cycle, INR amount, applicable taxes and activation terms before confirming payment. Contact support before purchase if the total or renewal conditions are unclear.'] },
      { heading: 'Cancel a subscription', paragraphs: ['An authorised organisation administrator can use Dashboard → Settings → Billing to request cancellation. Check the resulting subscription status and effective date. Contact support if cancellation fails or if you cannot access the account. Revoking an integration or deleting browser data does not cancel a subscription.', 'Cancellation stops future renewal according to the effective date confirmed for the subscription. It is not automatically a refund of an earlier payment. There is no separate cancellation fee introduced by this policy.'] },
      { heading: 'Request a refund or payment correction', paragraphs: ['For a duplicate or unauthorised charge, failed activation, service deficiency or other payment issue, contact support with your payment reference, date, amount, account email and a description. Never include a card number, CVV, PIN or OTP. Each request must be assessed under the purchase terms and applicable consumer law; this policy does not impose a blanket no-refund rule.', 'An accepted refund should be returned through the payment channel, subject to applicable law and processor timelines. Ask support for its status and reference. No processing time is guaranteed here until the operator has verified its workflow. Mandatory legal remedies take precedence over commercial refund conditions.'] },
    ],
  },
  'acceptable-use': {
    title: 'Acceptable use', description: 'Use connected systems lawfully and respect other people’s rights.',
    sections: [
      { heading: 'Authorised engineering work', paragraphs: ['Only access repositories, services, devices and data for which you have permission. Do not bypass access controls, steal credentials, distribute malware, conduct fraud, send unlawful communications, or interfere with other users or infrastructure. Security testing requires the system owner’s express authorisation.'] },
      { heading: 'Content and personal information', paragraphs: ['Do not upload or generate unlawful content, child sexual abuse material, non-consensual intimate imagery, deceptive impersonation, threats, or content that infringes intellectual property or privacy rights. Do not misuse personal data or use generated media to deceive people. Preserve required provenance and disclosures for synthetic content where applicable.', 'Do not upload government identifiers, health records, financial credentials or other sensitive information unless the processing is necessary, authorised and covered by an approved workflow. Never put secrets in public prompts or support messages.'] },
      { heading: 'Reporting and enforcement', paragraphs: ['Report suspected misuse through Grievances; security incidents can also be reported through Security. Include relevant resource links, timestamps and a concise explanation without redistributing illegal material. Reports and legal orders need assessment under the rules applicable to the service, including any urgent response requirements.', 'Necessary restrictions may include limiting access, disabling an integration or suspending an account. Where permitted, users should receive notice and an opportunity to challenge an error. Evidence may need to be preserved under law.'] },
    ],
  },
  security: {
    title: 'Security and vulnerability reporting', description: 'Report suspected vulnerabilities or incidents responsibly.',
    sections: [
      { heading: 'Report securely', paragraphs: ['Use the security contact below. Provide the affected URL or component, approximate time, minimal reproduction steps and potential impact. Remove tokens, personal data and customer content from examples. If sensitive evidence is needed, request an agreed secure channel first.'] },
      { heading: 'Testing boundaries', paragraphs: ['This page does not authorise penetration testing or access to another person’s data. Do not disrupt availability, exploit beyond the minimum demonstration, retain copied data or publish sensitive findings before coordinated remediation. There is no implied bug bounty or reward programme.'] },
      { heading: 'Incident response', paragraphs: ['Suspected incidents should be escalated promptly to the operator. Applicable regulator notifications, preservation of evidence and affected-user communications are separate operational duties; an email to support is not a report to CERT-In or another regulator. This page does not assert a security certification or that incident obligations have already been fulfilled.'] },
    ],
  },
  about: {
    title: 'About Escanor', description: 'A workspace for connected engineering systems.',
    sections: [
      { heading: 'What we build', paragraphs: ['Escanor brings together a web dashboard, connected cloud and developer services, local-machine workflows and AI-assisted engineering. The available functionality depends on your plan, workspace permissions and integrations.'] },
      { heading: 'Responsible use', paragraphs: ['Our goal is to give teams visibility and control over the systems they are authorised to operate. Review permissions, operational changes and generated output, and protect the information entrusted to your organisation.'] },
      { heading: 'Contact and operator', paragraphs: ['Use Support for product questions, Grievances for complaints, and Privacy requests for personal-data concerns. The operator information below identifies the business when configured. Escanor does not claim government endorsement or universal legal compliance.'] },
    ],
  },
  support: {
    title: 'Support and contact', description: 'Get help with access, integrations, billing and the product.',
    sections: [
      { heading: 'Getting help', paragraphs: ['Contact support below with your account email, a short description, affected feature and approximate time. Include a redacted error message or payment reference if relevant. Do not send passwords, access tokens, private repository contents, card data or identity documents.', 'The contact link opens your email application. You must send the email yourself; opening a link does not submit a ticket or confirm delivery. If the contact is unconfigured, this website cannot currently receive support requests through this page.'] },
      { heading: 'Other requests', paragraphs: ['Use Privacy requests for access, correction, erasure or withdrawal; Grievances for complaints and appeals; Security for vulnerability reports; and Refunds and cancellation for billing guidance.', 'You may ask for help understanding a notice or for an accessible format or Indian-language assistance. Availability and response arrangements need confirmation from the operator.'] },
    ],
  },
  grievances: {
    title: 'Grievances and complaints', description: 'Raise privacy, consumer, content or service complaints.',
    sections: [
      { heading: 'Contact the grievance officer', paragraphs: ['Send the grievance contact below your account reference, complaint category, relevant dates or URLs, preferred reply method and requested remedy. For an appeal, include the earlier correspondence. Share only necessary information and do not attach illegal content or credentials.', 'Keep a copy of your message and subsequent acknowledgement. Opening the email link does not lodge a complaint. Officer identity and monitored contact details must be configured before this channel can be relied upon.'] },
      { heading: 'Handling and escalation', paragraphs: ['Different complaint categories have different legal deadlines. Consumer e-commerce complaints, where those rules apply, require acknowledgement within 48 hours and redressal within one month. Privacy complaints under the applicable SPDI framework require redressal within one month. Content complaints and lawful orders may require much faster action under the currently applicable IT Rules; urgent reports must be triaged immediately.', 'If the response is unsatisfactory, you may use applicable consumer, court or regulatory remedies. DPDP grievance escalation and nomination provisions are subject to commencement and applicability. Nothing on this page requires you to waive a statutory remedy. The Legal page links to official resources.'] },
    ],
  },
  'privacy/requests': {
    title: 'Privacy requests', description: 'Request information, correction, erasure or withdrawal of consent.',
    sections: [
      { heading: 'Make a request', paragraphs: ['Email the privacy contact with the request type, your account email and the affected workspace or information. You can request access or information about processing, correction, erasure, withdrawal of consent, or raise a privacy grievance. Nomination under DPDP is subject to the relevant provisions becoming operative. An export format or unconditional erasure is not guaranteed by this page.', 'The contact link opens your email app; it does not submit a request until you send it. We may need proportionate identity or authority verification before disclosing or changing information. Do not send Aadhaar, PAN, passwords or secrets with the initial request.'] },
      { heading: 'Make a request in the app', paragraphs: ['Signed-in users can make a request, download a copy of their account records and manage optional consents under Dashboard → Settings → Security & data. Each request receives a reference number and is recorded with the time it was received. The operating targets are to acknowledge within 48 hours and to resolve within one month; they are targets, and the response will explain any reason a request cannot be completed in full.', 'The download covers account records only. It does not include content in connected services, AI conversation stores, logs or backups, and it never contains passwords or access tokens. A deletion request is carried out by a person after the legal retention position is checked; it is not an instant or automatic deletion.'] },
      { heading: 'Controls available now', paragraphs: ['Disconnect integrations in the dashboard and revoke access in the provider account to stop further access. Use the billing settings to stop subscription renewal. Sign out and clear site data on shared devices. These actions serve different purposes and do not substitute for requesting deletion of backend data.', 'For organisation-controlled information, include your workspace administrator so the request can be routed to the party responsible for the data. Withdrawal may prevent delivery of the feature requiring that processing; unrelated processing must not be bundled into that choice.'] },
      { heading: 'Retention and grievances', paragraphs: ['A deletion request may leave limited records that must be retained under applicable law, a legal hold or necessary dispute handling. The response should explain the relevant exception, scope and retention period. The operator must also address processors and backup expiry rather than promising immediate deletion of every copy.', 'If your request is unresolved, use the grievance channel. Rights under current law remain available; additional DPDP rights and Board escalation depend on the applicable commencement notifications.'] },
    ],
  },
};

export const legalLinks = [
  ['legal', 'Legal'], ['privacy', 'Privacy'], ['terms', 'Terms'], ['cookies', 'Cookies & storage'],
  ['privacy/requests', 'Privacy requests'], ['privacy/us', 'US privacy rights'], ['support', 'Support'], ['grievances', 'Grievances'],
  ['refunds', 'Refunds'], ['acceptable-use', 'Acceptable use'], ['security', 'Security'], ['about', 'About'],
] as const;

legalDocuments['privacy/us'] = {
  title: 'United States privacy notice',
  description: 'Additional information for US residents, read together with the Privacy policy.',
  sections: [
    { heading: 'Scope and applicable rights', paragraphs: [
      'US privacy law includes state and sector-specific rules. Depending on your residence, the processing and whether the operator is covered, you may have rights to know or access personal information, obtain a portable copy, correct inaccuracies, request deletion, opt out of sale or targeted advertising/sharing, limit certain sensitive-information uses, and appeal a denied request. Exercising an applicable privacy right must not result in unlawful discrimination.',
      'This notice does not claim that every state law applies to every customer or that Escanor is certified under CCPA, HIPAA, GLBA or any other framework. Information processed for your employer or another organisation may require the request to be routed to that organisation, without excluding rights that applicable law gives you.',
    ] },
    { heading: 'Categories, sources and recipients', paragraphs: [
      'The service can process identifiers such as account email and provider identifiers; commercial information such as plan and payment references; internet or network activity such as access and operational logs; and user-supplied workspace, code, prompt and support content. Login credentials and information within connected content can be sensitive. Sources include you, your organisation, connected providers and use of the service.',
      'The Privacy policy describes the purposes, recipient categories and retention considerations. The operator must validate actual collection, disclosures, sale/sharing and sensitive-information uses for the preceding twelve months before approving this notice. A service-provider disclosure is not automatically a sale, and a sale may involve consideration other than money. No unsupported blanket no-sale claim is made here.',
    ] },
    { heading: 'Requests, agents and appeals', paragraphs: [
      'Use Privacy requests or the privacy contact below to request access, correction, deletion, portability, an opt-out or a limitation. State the request type and, where relevant, your state of residence; provide only the information needed to identify the account. An authorised agent may submit a request with appropriate evidence of authority. Verification must be proportionate and must not be used to obstruct an opt-out that does not require identity verification.',
      'For covered CCPA requests to know, correct or delete, the applicable rules generally require confirmation of receipt within ten business days and a response within 45 calendar days, with an extension only where permitted and notified. Opt-out and other state deadlines differ. If a request is denied, ask for the reason and submit an appeal through Grievances where applicable; state regulators and other lawful remedies remain available.',
    ] },
    { heading: 'Sale, sharing, targeted advertising and browser signals', paragraphs: [
      'Use the privacy contact to communicate Do Not Sell or Share My Personal Information, targeted-advertising opt-outs, or a request to limit sensitive-information use where applicable. No advertising tracker was identified in the reviewed landing and root-provider flow. This is not a substitute for reviewing all providers and their contracts.',
      'A Global Privacy Control signal must be honoured for covered processing where required, including in California and Colorado. The reviewed app does not enable optional advertising trackers. Before adding any sale, sharing or targeted-advertising flow, the operator must connect opt-out signals and account choices to that processing and verify enforcement; these draft pages do not claim that an unimplemented preference workflow already exists.',
    ] },
    { heading: 'Children and regulated information', paragraphs: [
      'Escanor is intended for adults, not as a service directed to children under 13. Report suspected collection of a child’s information. An age statement alone does not satisfy COPPA when the rule applies. Do not use the service for regulated health, financial, biometric or similarly restricted processing unless the required agreements, permissions and controls have been established.',
    ] },
  ],
};
