// GENERATED by escanor-desktop/scripts/sync-phone-lib.mjs from packages/remote/src/phone/lan-pair.ts. Do not edit here.
import { approvalSecrets, b64u, ecdhGenerate, ecdhShared, open } from './secure';

/**
 * Whether a host is somewhere on the person's own network (or this device). The phone talks plain http/ws to a computer on the local
 * network (every message is sealed with the device key, so nothing readable crosses the air), and ONLY there: an address anywhere
 * else is ignored, so a mistyped or malicious address can never make the app send anything in the clear across the internet.
 */
export function isLocalAddress(addr: string): boolean {
  const host = addr.trim().replace(/^https?:\/\//i, '').replace(/[:/].*$/, '').toLowerCase();
  if (host === 'localhost' || host.endsWith('.local')) return true;
  const m = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(host);
  if (!m) return false;
  const [a, b, c, d] = m.slice(1).map(Number);
  if ([a, b, c, d].some((n) => n > 255)) return false;
  return a === 10 || a === 127 || (a === 192 && b === 168) || (a === 172 && b >= 16 && b <= 31) || (a === 169 && b === 254) || (a === 100 && b >= 64 && b <= 127);
}

export interface LanAskOptions {
  fetch?: typeof fetch;
  /** Called once, as soon as the computer has answered, with the number to compare with the one on its screen. */
  onConfirm?: (confirm: string) => void;
  pollMs?: number;
  /** Stop waiting (the person left the screen). */
  signal?: AbortSignal;
  now?: () => number;
  sleep?: (ms: number) => Promise<void>;
}

export interface LanAskResult {
  deviceId: string;
  key: Uint8Array;
  /** What the computer calls itself. */
  machine: { name: string } | null;
}

const withTimeout = <T>(p: Promise<T>, ms: number, what: string): Promise<T> =>
  new Promise((resolve, reject) => {
    const t = setTimeout(() => reject(new Error(`${what} timed out`)), ms);
    p.then((v) => (clearTimeout(t), resolve(v)), (e) => (clearTimeout(t), reject(e)));
  });

/**
 * The phone's half of pairing without a code. It needs only the computer's address: it asks, shows a confirmation number, and
 * waits for the person to approve on the computer. See `approvalSecrets` for why the number matters.
 */
export async function phoneAskLan(base: string, deviceName: string, o: LanAskOptions = {}): Promise<LanAskResult> {
  const doFetch = o.fetch ?? fetch;
  const sleep = o.sleep ?? ((ms: number) => new Promise<void>((r) => setTimeout(r, ms)));
  const now = o.now ?? Date.now;
  const call = async (path: string, init?: RequestInit) => withTimeout(doFetch(`${base}${path}`, { ...init, signal: o.signal }), 5000, 'The computer');
  const errorOf = async (res: Response, fallback: string) => ((await res.json().catch(() => ({}))) as { error?: string }).error ?? fallback;

  const mine = await ecdhGenerate();
  const res = await call('/pair/ask', { method: 'POST', body: JSON.stringify({ v: 1, device: { name: deviceName }, pub: b64u.encode(mine.pub) }) });
  if (res.status === 404) throw new Error('This computer does not allow pairing without a code. Update Escanor Desktop, or pair with the code instead.');
  if (!res.ok) throw new Error(await errorOf(res, `The computer refused (${res.status}).`));
  const started = (await res.json()) as { id: string; pub: string; ttlMs: number };
  const machinePub = b64u.decode(started.pub);
  const { key, confirm } = await approvalSecrets(await ecdhShared(mine.priv, machinePub), mine.pub, machinePub);
  o.onConfirm?.(confirm);

  const until = now() + Math.max(5000, started.ttlMs ?? 110_000) + 5000;
  while (now() < until) {
    if (o.signal?.aborted) throw new Error('Pairing was cancelled.');
    await sleep(o.pollMs ?? 1000);
    const poll = await call(`/pair/ask/${encodeURIComponent(started.id)}`);
    if (!poll.ok) throw new Error(await errorOf(poll, 'The computer lost track of this request. Try again.'));
    const st = (await poll.json()) as { status: string; deviceId?: string; sealedKey?: string; machine?: { name?: string } };
    if (st.status === 'denied') throw new Error('The computer said no.');
    if (st.status === 'expired') throw new Error('Nobody answered on the computer in time. Try again.');
    if (st.status === 'approved' && st.deviceId && st.sealedKey) {
      return { deviceId: st.deviceId, key: await open(key, st.sealedKey, `pair:${st.deviceId}`), machine: st.machine?.name ? { name: String(st.machine.name) } : null };
    }
  }
  throw new Error('Nobody answered on the computer in time. Try again.');
}
