#!/usr/bin/env node
// Copy the website's legal documents into the app, so Privacy, Terms and the rest read inside the app (and offline) instead of
// opening a browser. The website is the source: edit lib/legal-content.ts there, then run this and commit the result.
// Usage: node scripts/sync-legal.mjs [path-to-escanor-web]
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const web = resolve(process.argv[2] ?? resolve(import.meta.dirname, '../../escanor-web'));
const source = readFileSync(resolve(web, 'lib/legal-content.ts'), 'utf8');
const config = readFileSync(resolve(web, 'lib/legal-config.ts'), 'utf8');
const version = /POLICY_VERSION = '([^']+)'/.exec(config)?.[1];
const date = /POLICY_DATE = '([^']+)'/.exec(config)?.[1];
if (!version || !date) throw new Error('POLICY_VERSION / POLICY_DATE not found in lib/legal-config.ts');
const out = resolve(import.meta.dirname, '../packages/web/src/legal/content.ts');
writeFileSync(
  out,
  `// GENERATED by scripts/sync-legal.mjs from escanor-web/lib/legal-content.ts. Do not edit here: change the website, then re-run it.\n` +
    `export const POLICY_VERSION = '${version}';\nexport const POLICY_DATE = '${date}';\n\n${source}`,
);
console.log(`wrote ${out} (policy ${version})`);
